version: '3.7'

services:
  api:
    build:
      context: .
      target: build
    command: 'npm run compile:watch'
    environment:
        DB_URL: postgres://root:123@postgres/taps
    volumes:
      - ./src:/usr/src/app/src
      - ./jest.config.js:/usr/src/app/jest.config.js
  postgres:
    build: postgres
    volumes:
      - ./postgres/data/test:/var/lib/postgres/data
