version: '3.7'

services:
  builder:
    build:
      context: .
      target: build
    command: 'npm run compile:watch'
    volumes:
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
  api:
    build:
      context: .
      target: prod
    command: 'pm2-runtime start dist/index.js --watch'
    environment:
      NODE_ENV: 'docker'
      DB_URL: postgres://root:123@postgres/user
    volumes:
      - ./dist:/usr/src/app/dist
    ports:
      - '3000:3000'
  postgres:
    build: postgres
