version: '3.7'

services:
  api:
    build:
      context: .
      target: prod
    command: 'node dist/index.js'
    environment:
      NODE_ENV: 'production'
      DB_URL: postgres://root:123@postgres/user
    restart: always
    ports:
      - '80:80'
  postgres:
    build: postgres
